modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Event's Lootbags"
logoFile="eventslootbagslogo.png"
credits="Thanks to TurtyWurty and mcjty for their amazing tutorials!"
authors="${mod_authors}"
description='''${mod_description}'''
