modLoader="javafml" 
loaderVersion="[43,)"
license="MIT"
[[mods]]
modId="eventslootbags"
version="1.0"
displayName="Event's Lootbags"
logoFile="examplemod.png"
credits="Thanks to TurtyWurty for his amazin tutorials!"
authors="MCEventHorizon"

# The description text for the mod (multi line!) (#mandatory)
description='''
Lootbags mod based on Vanilla loot tables.
'''
