modLoader="javafml" 
loaderVersion="[43,)"
license="MIT"
[[mods]]
modId="eventslootbags"
version="1.0"
displayName="Event's Lootbags"
logoFile="eventslootbagslogo.png"
credits="Thanks to TurtyWurty for his amazing tutorials!"
authors="MCEventHorizon"

# The description text for the mod (multi line!) (#mandatory)
description='''
Lootbags mod that uses Vanilla Minecraft's loot table system.
'''
